language: zh
pipeline:
- name: JiebaTokenizer
- name: RegexFeaturizer
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - number
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
policies: null
